"""add_token_usage_to_messages

Revision ID: 55259b60a803
Revises: a1b2c3d4e5f6
Create Date: 2026-06-19 18:10:05.672826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '55259b60a803'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_agent_memories_context_sig', table_name='agent_memories', postgresql_using='gin')
    op.drop_index('idx_agent_memories_embedding', table_name='agent_memories', postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index('idx_agent_memories_project_id', table_name='agent_memories')
    op.add_column('messages', sa.Column('token_usage', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'token_usage')
    op.create_index('idx_agent_memories_project_id', 'agent_memories', ['project_id'], unique=False)
    op.create_index('idx_agent_memories_embedding', 'agent_memories', ['embedding'], unique=False, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_index('idx_agent_memories_context_sig', 'agent_memories', ['context_signature'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
