"""add code_chunks with pgvector

Revision ID: ed9531b4a577
Revises: 4d5469d9a0f3
Create Date: 2026-05-24 12:02:36.592451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
import pgvector 
# revision identifiers, used by Alembic.
revision: str = 'ed9531b4a577'
down_revision: Union[str, None] = '4d5469d9a0f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('start_line', sa.Integer(), nullable=False),
    sa.Column('end_line', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('chunk_type', sa.String(length=50), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('indexed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'file_path', 'start_line', 'end_line')
    )

    # In your generated migration file, add to upgrade():

    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    op.execute("""
        CREATE INDEX idx_code_chunks_embedding
        ON code_chunks
        USING ivfflat (embedding vector_cosine_ops)
        WITH (lists = 100)
    """)

    op.execute("""
        ALTER TABLE code_chunks
        ADD COLUMN IF NOT EXISTS content_tsv tsvector
        GENERATED ALWAYS AS (to_tsvector('english', content)) STORED
    """)

    op.execute("""
        CREATE INDEX idx_code_chunks_tsv
        ON code_chunks USING GIN (content_tsv)
    """)

    op.execute("""
        CREATE INDEX idx_code_chunks_project
        ON code_chunks (project_id)
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('code_chunks')
    # ### end Alembic commands ###
