"""add_user_settings

Revision ID: f4176c07dc24
Revises: ed9531b4a577
Create Date: 2026-06-11 22:07:06.353163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f4176c07dc24'
down_revision: Union[str, None] = 'ed9531b4a577'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('api_key', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.drop_index('idx_code_chunks_tsv', table_name='code_chunks', postgresql_using='gin')
    op.drop_column('code_chunks', 'content_tsv')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code_chunks', sa.Column('content_tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english'::regconfig, content)", persisted=True), autoincrement=False, nullable=True))
    op.create_index('idx_code_chunks_tsv', 'code_chunks', ['content_tsv'], unique=False, postgresql_using='gin')
    op.drop_table('user_settings')
    # ### end Alembic commands ###
